### ISSUE TITLE
Fedora 33: /proc/sys/write_wakeup_threshold: No such file or directory

### ISSUE THREAD

**Issue by agross** [robertdebock/ansible-role-haveged#4]
## Describe the bug

When installing this in my playbook I receive the following error: `sysctl: cannot stat /proc/sys/write_wakeup_threshold: No such file or directory`

The sysctl is located at a different path:

```sh
$ find /proc/sys/ -name write_wakeup_threshold
/proc/sys/kernel/random/write_wakeup_threshold

$ uname -a
Linux playground 5.9.11-200.fc33.x86_64 #1 SMP Tue Nov 24 18:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: Apply common configuration to all nodes
  hosts: "{{ target | default('prod') }}"
  become: true
  roles:
    - name: robertdebock.haveged
```

requirements.yml:

```
- src: robertdebock.haveged
```

## Output

```
TASK [robertdebock.haveged : include assert.yml] ********************************************************************************************************
included: /Users/agross/.ansible/roles/robertdebock.haveged/tasks/assert.yml for playground.home.therightstuff.de

TASK [robertdebock.haveged : test if haveged_write_wakeup_threshold is set correctly] *******************************************************************
ok: [playground.home.therightstuff.de]

TASK [robertdebock.haveged : install haveged] ***********************************************************************************************************
ok: [playground.home.therightstuff.de]

TASK [robertdebock.haveged : set write_wakeup_threshold] ************************************************************************************************
fatal: [playground.home.therightstuff.de]: FAILED! => changed=false
  msg: |-
    Failed to reload sysctl: kernel.random.write_wakeup_threshold = 1024
    sysctl: cannot stat /proc/sys/write_wakeup_threshold: No such file or directory

PLAY RECAP **********************************************************************************************************************************************
playground.home.therightstuff.de : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

## Environment

- Control node OS: macOS
- Control node Ansible version: ansible 2.10.3
- Managed node OS: Fedora 33

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by agross** [comment]
Seems like I still had an old version from Ansible Galaxy installed.

**Comment by agross** [comment]
Sorry to tell you that this seems to be caused by something entirely different. Setting the sysctl works if the role is included in a playbook like this:

```yaml
- name: Apply common configuration to all nodes
  hosts: something
  become: true
  roles:
    - name: robertdebock.haveged
```

But when the haveged role is added as a dependency the error I reported is thrown:

roles/something/meta/main.yml:
```yaml
allow_duplicates: false
dependencies:
  - name: robertdebock.haveged
```

Very strange.
